apiRules:
- include:
    uidRegex: ^UIWitches
    type: Namespace
- include:
    uidRegex: ^UIWitches.Editor
    type: Namespace
- include:
    uidRegex: ^Global
    type: Namespace
- exclude:
    uidRegex: .*
    type: Namespace
